"""Update Ticket model

Revision ID: 39368675fa5e
Revises: 
Create Date: 2025-01-04 07:54:13.846971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39368675fa5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ticket_category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('ticket_category')

    # ### end Alembic commands ###
